version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    env_file:
      - .env
    working_dir: /usr/src/ediary-api
    restart: always
    command: bash -c "npm install --only=prod && npm run build && npm run start"
    volumes:
      - ./build/:/usr/src/ediary-api/build/
      - ./package.json:/usr/src/ediary-api/package.json
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo